"""add avatar_url to creators

Revision ID: ba209162b44d
Revises: 0002_cache_table
Create Date: 2026-07-04 23:36:52.445354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba209162b44d'
down_revision: Union[str, None] = '0002_cache_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cache')
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    op.create_table('cache',
    sa.Column('key', sa.VARCHAR(length=128), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###
